"""Plot cross-model factual QA text-feature driver figures.

Inputs are the text-feature driver outputs generated by
src/54_analyze_factual_text_feature_drivers.py.

Outputs are written to token_analysis_figures/.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import pandas as pd
from scipy import stats


ROOT = Path(__file__).resolve().parents[1]
FIG_DIR = ROOT / "token_analysis_figures"

MODEL_FILES = {
    "GPT/main": {
        "base": ROOT / "outputs" / "factual_text_feature_base_fixed_factual.csv",
        "corr": ROOT / "outputs" / "factual_text_feature_driver_correlations_fixed_factual.csv",
    },
    "Llama": {
        "base": ROOT / "outputs" / "llama_factual_text_feature_base_fixed_factual.csv",
        "corr": ROOT / "outputs" / "llama_factual_text_feature_driver_correlations_fixed_factual.csv",
    },
    "Qwen": {
        "base": ROOT / "qwen" / "outputs" / "factual_text_feature_base_fixed_factual.csv",
        "corr": ROOT / "qwen" / "outputs" / "factual_text_feature_driver_correlations_fixed_factual.csv",
    },
}

KEY_FEATURES = [
    "mean_output_token_edit_distance_norm",
    "median_output_token_edit_distance_norm",
    "output_length_delta_tokens",
    "output_length_ratio",
    "factual_score_delta",
    "containment_rate_delta",
    "question_token_edit_distance_norm",
    "cue_disruption",
]

FEATURE_LABELS = {
    "mean_output_token_edit_distance_norm": "Mean output token edit distance",
    "median_output_token_edit_distance_norm": "Median output token edit distance",
    "output_length_delta_tokens": "Output length delta",
    "output_length_ratio": "Output length ratio",
    "factual_score_delta": "Reference token-F1 delta",
    "containment_rate_delta": "Reference containment delta",
    "question_token_edit_distance_norm": "Question token edit distance",
    "cue_disruption": "Cue disruption",
    "noise_corrected_drift": "Noise-corrected drift",
}

MODEL_COLORS = {
    "GPT/main": "#4C78A8",
    "Llama": "#F58518",
    "Qwen": "#54A24B",
}


def load_data() -> tuple[pd.DataFrame, pd.DataFrame]:
    bases = []
    corrs = []
    for model, paths in MODEL_FILES.items():
        base = pd.read_csv(paths["base"])
        corr = pd.read_csv(paths["corr"])
        base["model"] = model
        corr["model"] = model
        bases.append(base)
        corrs.append(corr)
    return pd.concat(bases, ignore_index=True), pd.concat(corrs, ignore_index=True)


def save_fig(path: Path) -> None:
    plt.tight_layout()
    plt.savefig(path, dpi=300, bbox_inches="tight")
    plt.close()


def plot_correlation_heatmap(corr: pd.DataFrame) -> None:
    matrix = (
        corr[corr["feature"].isin(KEY_FEATURES)]
        .pivot(index="feature", columns="model", values="spearman_rho")
        .loc[KEY_FEATURES, ["GPT/main", "Llama", "Qwen"]]
    )
    labels = [FEATURE_LABELS.get(feature, feature) for feature in matrix.index]

    fig, ax = plt.subplots(figsize=(9, 6))
    image = ax.imshow(matrix.values, cmap="RdBu_r", vmin=-0.75, vmax=0.75, aspect="auto")
    ax.set_xticks(range(len(matrix.columns)))
    ax.set_xticklabels(matrix.columns)
    ax.set_yticks(range(len(labels)))
    ax.set_yticklabels(labels)
    ax.set_title("Spearman correlation with factual QA paraphrase drift")

    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            value = matrix.iloc[i, j]
            color = "white" if abs(value) > 0.45 else "black"
            ax.text(j, i, f"{value:.2f}", ha="center", va="center", color=color, fontsize=9)

    cbar = fig.colorbar(image, ax=ax, fraction=0.046, pad=0.04)
    cbar.set_label("Spearman rho")
    save_fig(FIG_DIR / "fig1_cross_model_feature_correlation_heatmap.png")


def plot_output_vs_prompt_strength(corr: pd.DataFrame) -> None:
    summary = (
        corr.groupby(["model", "feature_family"])["spearman_rho"]
        .apply(lambda s: s.abs().mean())
        .reset_index(name="mean_abs_rho")
    )
    models = ["GPT/main", "Llama", "Qwen"]
    families = ["output", "prompt"]
    x = range(len(models))
    width = 0.36

    fig, ax = plt.subplots(figsize=(8, 5))
    for offset, family in zip([-width / 2, width / 2], families):
        values = [
            float(summary[(summary["model"] == model) & (summary["feature_family"] == family)]["mean_abs_rho"].iloc[0])
            for model in models
        ]
        bars = ax.bar([pos + offset for pos in x], values, width=width, label=f"{family}-side")
        for bar, value in zip(bars, values):
            ax.text(bar.get_x() + bar.get_width() / 2, value + 0.01, f"{value:.2f}", ha="center", fontsize=9)

    ax.set_xticks(list(x))
    ax.set_xticklabels(models)
    ax.set_ylabel("Mean absolute Spearman rho")
    ax.set_ylim(0, 0.58)
    ax.set_title("Output-side features are stronger than prompt-side features")
    ax.legend(frameon=False)
    save_fig(FIG_DIR / "fig2_output_vs_prompt_feature_strength.png")


def add_regression_line(ax: plt.Axes, x: pd.Series, y: pd.Series, color: str) -> tuple[float, float]:
    sub = pd.DataFrame({"x": x, "y": y}).dropna()
    slope, intercept, r_value, p_value, _ = stats.linregress(sub["x"], sub["y"])
    x_min, x_max = sub["x"].min(), sub["x"].max()
    ax.plot([x_min, x_max], [intercept + slope * x_min, intercept + slope * x_max], color=color, linewidth=2)
    rho, p = stats.spearmanr(sub["x"], sub["y"])
    return float(rho), float(p)


def scatter_grid(base: pd.DataFrame, feature: str, filename: str, title: str, x_label: str) -> None:
    models = ["GPT/main", "Llama", "Qwen"]
    fig, axes = plt.subplots(1, 3, figsize=(14, 4), sharey=True)
    for ax, model in zip(axes, models):
        sub = base[base["model"] == model]
        color = MODEL_COLORS[model]
        ax.scatter(sub[feature], sub["noise_corrected_drift"], s=34, color=color, alpha=0.78, edgecolor="white", linewidth=0.6)
        rho, p = add_regression_line(ax, sub[feature], sub["noise_corrected_drift"], color)
        ax.set_title(f"{model}\nrho={rho:.2f}, p={p:.3g}", fontsize=10)
        ax.set_xlabel(x_label)
        ax.grid(alpha=0.25)
    axes[0].set_ylabel("Noise-corrected drift")
    fig.suptitle(title, fontsize=13)
    save_fig(FIG_DIR / filename)


def plot_summary_table(corr: pd.DataFrame, base: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for model in ["GPT/main", "Llama", "Qwen"]:
        model_base = base[base["model"] == model]
        model_corr = corr[corr["model"] == model].set_index("feature")
        rows.append(
            {
                "model": model,
                "mean_ncp": model_base["noise_corrected_drift"].mean(),
                "mean_output_length_delta": model_base["output_length_delta_tokens"].mean(),
                "mean_output_length_ratio": model_base["output_length_ratio"].mean(),
                "mean_output_edit_rho": model_corr.loc["mean_output_token_edit_distance_norm", "spearman_rho"],
                "length_delta_rho": model_corr.loc["output_length_delta_tokens", "spearman_rho"],
                "f1_delta_rho": model_corr.loc["factual_score_delta", "spearman_rho"],
                "containment_delta_rho": model_corr.loc["containment_rate_delta", "spearman_rho"],
            }
        )
    summary = pd.DataFrame(rows)
    summary.to_csv(FIG_DIR / "cross_model_text_feature_summary.csv", index=False)
    return summary


def write_readme(summary: pd.DataFrame) -> None:
    lines = [
        "# Token Analysis Figures",
        "",
        "These figures summarize the text-level driver analysis for fixed factual QA paraphrasing across GPT/main, Llama, and Qwen.",
        "",
        "## Recommended figure use",
        "",
        "1. `fig1_cross_model_feature_correlation_heatmap.png`: main overview figure. It shows that output edit-distance and output expansion are consistently stronger than containment change.",
        "2. `fig2_output_vs_prompt_feature_strength.png`: compact evidence that output-side features have higher mean absolute correlation with drift than prompt-side features in all three models.",
        "3. `fig3_output_edit_distance_vs_drift.png`: strongest scatter evidence. Use this to show drift is directly visible as generated-output divergence.",
        "4. `fig4_output_length_delta_vs_drift.png`: supports the answer expansion / longer-output interpretation.",
        "5. `fig5_reference_f1_delta_vs_drift.png`: shows that reduced compact reference-answer overlap tracks drift.",
        "6. `fig6_containment_delta_vs_drift.png`: negative-control style figure. It shows containment change is weak, so drift is not simply reference-answer disappearance.",
        "",
        "## Cross-model summary",
        "",
        "| Model | Mean NCP | Output length delta | Output length ratio | Output edit rho | Length rho | F1 delta rho | Containment rho |",
        "|---|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for _, row in summary.iterrows():
        lines.append(
            "| {model} | {mean_ncp:.4f} | {mean_output_length_delta:.3f} | {mean_output_length_ratio:.3f} | "
            "{mean_output_edit_rho:.3f} | {length_delta_rho:.3f} | {f1_delta_rho:.3f} | {containment_delta_rho:.3f} |".format(
                **row
            )
        )
    lines.extend(
        [
            "",
            "## Main interpretation",
            "",
            "Across all three branches, fixed factual QA paraphrase drift is most strongly associated with generated-output divergence, output length expansion, and reduced compact reference-answer overlap. Reference containment changes are weak, which supports the interpretation that the residual drift reflects answer-scope and response-style changes rather than simple factual-answer disappearance.",
            "",
        ]
    )
    (FIG_DIR / "README.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    FIG_DIR.mkdir(exist_ok=True)
    base, corr = load_data()

    plot_correlation_heatmap(corr)
    plot_output_vs_prompt_strength(corr)
    scatter_grid(
        base,
        "mean_output_token_edit_distance_norm",
        "fig3_output_edit_distance_vs_drift.png",
        "Output token edit distance vs drift",
        "Mean output token edit distance",
    )
    scatter_grid(
        base,
        "output_length_delta_tokens",
        "fig4_output_length_delta_vs_drift.png",
        "Output length expansion vs drift",
        "Output length delta (tokens)",
    )
    scatter_grid(
        base,
        "factual_score_delta",
        "fig5_reference_f1_delta_vs_drift.png",
        "Reference token-F1 delta vs drift",
        "Reference token-F1 delta",
    )
    scatter_grid(
        base,
        "containment_rate_delta",
        "fig6_containment_delta_vs_drift.png",
        "Reference containment delta vs drift",
        "Reference containment delta",
    )
    summary = plot_summary_table(corr, base)
    write_readme(summary)

    print(f"Wrote figures to {FIG_DIR}")


if __name__ == "__main__":
    main()
